## An√°lisis resultados

In [2]:
import pandas as pd

res = pd.read_csv("output/result_sample60.csv")
display(res.head(10))

,protein_ID,FASTA,small_mol_name,SMILES,score
0,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Nitazoxanide'],CC(=O)OC1=CC=CC=C1C(=O)NC2=NC=C(S2)[N+](=O)[O-],11.132530
1,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Abacavir'],C1CC1NC2=C3C(=NC(=N2)N)N(C=N3)C4CC(C=C4)CO,10.705376
2,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Erythropoietin'],CCCCC1=NC(=C(N1CC2=CC=C(C=C2)C3=CC=CC=C3C4=NN=...,10.690286
3,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Dasabuvir'],CC(C)(C)C1=CC(=CC(=C1OC)C2=CC3=C(C=C2)C=C(C=C3...,10.658155
4,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Dasabuvir'],CC(C)(C)C1=CC(=CC(=C1OC)C2=CC3=C(C=C2)C=C(C=C3...,10.658155
5,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Doravirine'],CN1C(=NNC1=O)CN2C=CC(=C(C2=O)OC3=CC(=CC(=C3)C#...,10.656710
6,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Doravirine'],CN1C(=NNC1=O)CN2C=CC(=C(C2=O)OC3=CC(=CC(=C3)C#...,10.656710
7,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Velpatasvir'],CC1CCC(N1C(=O)C(C(C)C)NC(=O)OC)C2=NC3=C(N2)C=C...,10.646124
8,6W41_C,RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...,['Velpatasvir'],CC1CCC(N1C(=O)C(C(C)C)NC(=O)OC)C2=NC3=C(N2)C=C...,10.631855
9,6YB7_A,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,['Rilpivirine'],CC1=CC(=CC(=C1NC2=NC(=NC=C2)NC3=CC=C(C=C3)C#N)...,10.624742

In [3]:
display(res[["protein_ID", "small_mol_name","score"]].head(10))

  protein_ID      small_mol_name      score
0     6YB7_A    ['Nitazoxanide']  11.132530
1     6YB7_A        ['Abacavir']  10.705376
2     6YB7_A  ['Erythropoietin']  10.690286
3     6YB7_A       ['Dasabuvir']  10.658155
4     6YB7_A       ['Dasabuvir']  10.658155
5     6YB7_A      ['Doravirine']  10.656710
6     6YB7_A      ['Doravirine']  10.656710
7     6YB7_A     ['Velpatasvir']  10.646124
8     6W41_C     ['Velpatasvir']  10.631855
9     6YB7_A     ['Rilpivirine']  10.624742

#### De los 10 primeros resultados, 9 son de la proteasa. Score medio proteasa 10.44, score medio esp√≠cula: 10.29.

In [4]:
res.describe()

           score
count  60.000000
mean   10.299696
std     0.304033
min     9.610174
25%    10.069351
50%    10.326928
75%    10.523374
max    11.132530

In [5]:
espicula =  res[res["protein_ID"] == "6W41_C"]
proteasa =  res[res["protein_ID"] == "6YB7_A"]

In [6]:
display(espicula.describe())
display(proteasa.describe())

           score
count  34.000000
mean   10.191082
std     0.243887
min     9.703468
25%    10.000333
50%    10.265013
75%    10.361399
max    10.631855

           score
count  26.000000
mean   10.441729
std     0.320328
min     9.610174
25%    10.299104
50%    10.533177
75%    10.654063
max    11.132530

In [7]:
espicula.max()

protein_ID                                                   6W41_C
FASTA             RVQPTESIVRFPNITNLCPFGEVFNATRFASVYAWNRKRISNCVAD...
small_mol_name                                        ['Zanamivir']
SMILES            COC1=CC(=CC(=C1OC)OC)C2C3C(COC3=O)C(C4=CC5=C(C...
score                                                       10.6319
dtype: object

In [8]:
proteasa.max()

protein_ID                                                   6YB7_A
FASTA             SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...
small_mol_name                                     ['Voxilaprevir']
SMILES            CN1C(=NNC1=O)CN2C=CC(=C(C2=O)OC3=CC(=CC(=C3)C#...
score                                                       11.1325
dtype: object